Metrics/AbcSize:
  Exclude:
    - 'lib/valkyrie/persistence/fedora/persister/model_converter.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/valkyrie/persistence/postgres/query_service.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/valkyrie/persistence/fedora/persister.rb'
