require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
Style/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - '**/*.rake'
Style/PredicateName:
  Exclude:
    - "app/controllers/catalog_controller.rb"
    - "lib/valkyrie/model.rb"
    - "lib/valkyrie/persistence/solr/queries/default_paginator.rb"
    - "lib/valkyrie/persistence/active_fedora/queries/default_paginator.rb"
Style/MethodMissing:
  Exclude:
    - "lib/valkyrie/persistence/active_fedora/resource_factory.rb"
Metrics/BlockLength:
  Exclude:
    - 'config/environments/**/*'
    - 'spec/**/*'
    - 'config/initializers/*'
    - 'config/routes.rb'
    - 'lib/valkyrie/specs/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/dev.rake'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
RSpec/FilePath:
  Exclude:
    - 'spec/adapters/registered_adapter_spec.rb'
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/javascripts/jasmine_spec.rb'
    - 'spec/tasks/rake_spec.rb'
    - 'spec/jobs/event_jobs_spec.rb'
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'
    - 'spec/requests/**/*'
