# This is a sample config file that points to a solr server for each environment
development:
  url: http://localhost:8985/solr/hydra-test
test:
  url: <%= "http://localhost:#{ENV['TEST_JETTY_PORT'] || 8985}/solr/hydra-test" %>
production: &production
  url: <%= ENV["PLUM_SOLR_URL"] %>
staging:
  <<: *production
